COMPONENT_ADD_INCLUDEDIRS := include
COMPONENT_PRIV_INCLUDEDIRS := private_include

COMPONENT_LIBRARY :=
COMPONENT_ADD_LDFLAGS :=
COMPONENT_LDFLAGS :=

COMPONENT_OWNBUILDTARGET := 1
COMPONENT_OWNCLEANTARGET := 1

.PHONY: build
build:

.PHONY: clean
clean:
